### ISSUE TITLE
crash on both os (ios and android) when a parsing error ocured

### ISSUE THREAD

**Issue by macartigan** [jeffreymendez1993/react-native-webview-readability#13] opened 2021-04-15 10:52 UTC
Hello,

only with a device (don't crash with simulators)

react-native-reader version :  0.5.3 and 0.3.3 and 0.3.2 
"react-native": "0.64.0",
"react-native-webview": "^11.3.1",

**Comment by j-mendez** [comment] 2021-04-15 11:55
https://github.com/j-mendez/react-native-reader/issues/14 is this ticket related @clind-arthur?. Can you try out v0.5.4 to see if the issue persist.

**Comment by macartigan** [comment] 2021-04-15 12:35
it can be related, yes. When I am on my emulator (ios or android), I see the error message 
<img width="444" alt="image" src="https://user-images.githubusercontent.com/61415619/114869893-d0c53480-9df7-11eb-982f-69b9cd387d2a.png">

But on a real device (ios or android), the app crash.

**Comment by j-mendez** [comment] 2021-04-15 18:24
@clind-arthur having trouble reproducing, can I see a picture of the component usage? I just pushed a new release to validate `onError` prop usage.

**Comment by j-mendez** [comment] 2021-04-15 23:02
closing since issue is cors related outside of the project. In order to bypass cors try a proxy or domain front. You can use https://github.com/A11yWatch/node-iframe in order to bypass most issues.

**Closed as completed by j-mendez** 2021-04-15 23:02 UTC
